---

antora:
  name: modules
  dir: www
  modules:
    - name: 01-the-openshift-platform
      label: "Introduction"
      solveButton: false
    - name: 02-accessing-the-cluster
      label: "Accessing the cluster"
      solveButton: false
    - name: 03-deploying-an-application
      label: "Deploy the Application"

tabs:
  - name: ">_ terminal"
    url: /wetty
  # - name: "Asciidoc Doc"
  #   url: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
  #   external: true
